### PR TITLE
Handle callback queries in conversations

### PR DESCRIPTION
**Pull request by SergiX44**
This, should partially fix the issue #22, BUT it's also true that if the cbquery match some listener, the conversation is discarded. As I written in the issue, if for example we want force the user to follow conversation/step by step wizard it can simply escape by typing any other command.
@cheeghi Feel free to edit this branch if you have a better solution 😄

### CODE REVIEW

**Comment by cheeghi** [comment]
Hi, maybe I'm missing something, but I didn't get the reason to clear the conversation state if a callback query listener is found, we can call both the listeners and the conversation handler. Instead for text messages, you're proposing to prioritize the conversation instead of the listener, but this means that if someone in the middle of a conversation wants to escape and sends **/mycommand**, we should call the conversation handler and ignore the command listener. How botman deals with this? (I'm just wondering, to fine the best solution)

**Comment by SergiX44** [comment]
Botman ignores other handlers if it's in the middle of a conversation, but you set some handlers that allows to "escape" if you are in a conversation: https://botman.io/2.0/conversations (Skip or Stop Conversations section). Maybe here, we can try to evaluate the conversation **before** calling a listener, and maybe add a parameter on the `nextStep` method like `nextStep($callback, bool $skipListeners = false)` that allow the next step to be called without searching for handlers. In this way we can enforce a step or keep the user free of interrupting a coversation when he want.

**Comment by cheeghi** [comment]
It may be a good solution actually, I'm a bit worried about retrieving the conversation. Right now ```ListenerResolver::resolve()``` resolves the listeners looking inside the in-memory array ```ListenerCollector::$listeners```, having to check inside the cache for possible conversation before returning the resolved listeners means waiting for the promise response that would make the whole method **promise-based**. So, it may be tricky, but we can see how it goes.

**Comment by cheeghi** [comment]
I made the implementation, I also moved the conversation methods in a dedicated class. If you may take a look and give me a feedback I would really appreciate

**Comment by SergiX44** [comment]
Looks good! I didn't tested on a real world bot but tests and logic seems fine

**Pull request merged**
