### PR TITLE
Support regex as dynamic parameters

### PR DESCRIPTION
**Pull request by SergiX44**
This pr aims to add the support to simple parameters for the callable of commands and text events, like:

```php
$bot->onText('My name is {name}, I live in {city}', function (Context $ctx, $name, $city) { ... });
// and
$bot->onCommand('start {token}', function (Context $ctx, $token) { ... });
```
As always, suggestions/changes are welcome

### CODE REVIEW

**Comment by cheeghi** [comment]
Hi, sorry for the late reply. That's a very cool feature! I added it also for cb queries. Can you add a comment explaining the regex? As you know they aren't much self-explanatory 😅

**Comment by cheeghi** [comment]
Thanks! Going to merge the PR and release a 0.6.2.

**Comment by SergiX44** [comment]
@cheeghi I've just noticed that a unit test is failing, about the callback queries, if you look at travis

**Comment by cheeghi** [comment]
Ah yeah, there was an error in the unit test. Fixed in develop, thanks!

**Pull request merged**
